src/Entity/Group.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GroupRepository")
 */
class Group
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $creator_id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="userGroups")
     */
    private $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatorId(): ?string
    {
        return $this->creator_id;
    }

    public function setCreatorId(string $creator_id): self
    {
        $this->creator_id = $creator_id;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addUserGroup($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeUserGroup($this);
        }

        return $this;
    }




}

src/Form/GroupType.php
<?php

namespace App\Form;

use App\Entity\Group;
use App\Entity\User;
use Doctrine\DBAL\Types\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\SubmitButton;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GroupType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
         /*   ->add('users',EntityType::class,[
              'class'=>User::class,
              'multiple'=>true,
              'choice_label'=> function($user){
                  return $user->getPseudo();
              }
            ])*/
          ->add('submit',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Group::class,
        ]);
    }
}

src/Controller/GroupController.php
<?php

namespace App\Controller;

use App\Entity\Group;
use App\Entity\User;
use App\Form\GroupType;

use App\Repository\GroupRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

use Symfony\Component\Routing\Annotation\Route;

/**
 * Class GroupController
 * @package App\Controller
 * @Route("/group",name="group_")
 */
class GroupController extends AbstractController
{
  private $groupRepository;
  private $entityManager;

  /**
   * UserController constructor.
   * @param $userRepository
   */
  public function __construct(EntityManagerInterface $entityManager, GroupRepository $groupRepository)
  {
    $this->groupRepository = $groupRepository;
    $this->entityManager = $entityManager;

  }
  /**
     * @Route("/list", name="list")
     */
    public function index()
    {
        return $this->render('group/index.html.twig', [
            'controller_name' => 'GroupController',
        ]);
    }

   /**
     * @Route("/new/{id}",name="new")
    */
    public function new ($id,Request $request){
      $group = new Group();
      $form = $this->createForm(GroupType::class,$group);
      $form->handleRequest($request);
      if($form->isSubmitted() && $form->isValid()){
         $group->setCreatorId($id);
      //   dump($group);die;
        $this->entityManager->persist($group);
        $this->entityManager->flush();

        $this->addFlash('success', "new group has been created");

        return $this->redirectToRoute('user');
      }

      return $this->render('user/new.html.twig', [
        'form' => $form->createView(),
      ]);
    }
}

templates/group/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello GroupController!{% endblock %}

{% block body %}

  <div class="example-wrapper">
    <ul>
        <p><a href="{{ path('group_new') }}">Créer un groupe</a></p>
      {% for group in groups %}
        <a href="{{ path('group_delete',{'id': group.id}) }}">Delete</a>
        <a href="{{ path('group_update',{'id':group.id}) }}">update</a>


        <span>Group :</span>
        <li>id : {{ group.id }} <br>
            creator id : {{ group.creatorId }} <br>
            name : {{ group.getName }} <br>
             membres : {% for user in  group.users %}
                       {% if user.id is defined  %}
                            {{ user.pseudo  }}
                            {%  if group.creatorId == user.id %}
                              (ADMIN)
                            {% endif %}
                       {% endif %}
            ---
                       {% endfor %}
           <br>
            projects : {% for project in  group.projects %}
                        {% if project.id is defined  %}

                        {{ project.id  }}
                            ---{{ project.name }}
                        {% endif %}
                        ---
                      {% endfor %}
        </li>


      {% endfor %}
    </ul>

  </div>
{% endblock %}

templates/group/new.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    {{ form (form) }}

{% endblock %}